// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ZufRV-4HVzQG_H9a2tGG61wwzVL_avo',
    appId: '1:452370677546:web:4a420f38f68692320fe853',
    messagingSenderId: '452370677546',
    projectId: 'railway-booking-system---dbms',
    authDomain: 'railway-booking-system---dbms.firebaseapp.com',
    storageBucket: 'railway-booking-system---dbms.appspot.com',
    measurementId: 'G-W8F9HH4628',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMibobo_IVfRnRtIfNtlDqXggGxm7mOM',
    appId: '1:452370677546:android:e22742a9c66cb4f50fe853',
    messagingSenderId: '452370677546',
    projectId: 'railway-booking-system---dbms',
    storageBucket: 'railway-booking-system---dbms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICvdywDKVCObjibEOm0wOCyvG9G87H9U',
    appId: '1:452370677546:ios:b778f9f31883d1e70fe853',
    messagingSenderId: '452370677546',
    projectId: 'railway-booking-system---dbms',
    storageBucket: 'railway-booking-system---dbms.appspot.com',
    iosClientId: '452370677546-8p735gpvj3ao9hp7rsi36ksaojdo3dvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxpro',
  );
}
